### ISSUE TITLE
Adding custom syntax highlighting

### ISSUE THREAD

**Issue by mhshaaban** [MohamedYoussouf/ramz#2]
@MohamedYoussouf @adyouri This is probably easier for you to explain how to do. I want to use this in-browser editor to do some Arabic markdown writing but I don't know how I could add a custom syntax highlighting. I understand I could throw in prismjs and add a custom language through it. But how could I add prismjs to your in-browser editor?

**Comment by MohamedYoussouf** [comment]
You can import prismjs into `app.js` as following
```
import Prism from "prismjs";
import "../../node_modules/prismjs/themes/prism.css";
```

Then call it
```
componentDidMount() {
    Prism.highlightAll();
}
```
